### PR TITLE
There are no languages iw or in

### PR DESCRIPTION
**Pull request by razzeee**
See https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

### CODE REVIEW

**Comment by jamontes** [comment]
Hi Razzeee,

Please, have a look at this list, which is what i was based on to find the language codes: http://kodi.wiki/view/List_of_language_codes_%28ISO-639:1988%29

If the hebrew and indonesian codes from the Kodi wiki list aren't correct, please let me know and i'll be glad to accept your pull request. In that case, please, don't forget to let Team Kodi know as well of the mistake in order to keep the wiki entry updated.

Thanks a lot for review and improve my code.

jamontes.

**Comment by razzeee** [comment]
Well I'm afraid that the docs are wrong on hebrew at least. I'll chage the wiki to reflect that.
https://github.com/xbmc/xbmc/blob/master/xbmc/utils/LangCodeExpander.cpp#L1309

Indonesian is also wrong should be id.
https://github.com/xbmc/xbmc/blob/master/xbmc/utils/LangCodeExpander.cpp#L1322

**Comment by jamontes** [comment]
Thanks for the quick update!

As it's being long without making and update to the add-on with the translations from Transifex, i'll update the po files and take the chance to update the addon.xml file with the "he" and "id" entries as well, so the add-on will be fine on the next PR shortly. That's much better than just remove those wrong language code entries, as they are already supported into the add-on for their respective country websites.

Thanks a lot for your help and time.

Best regards,

jamontes.

**Comment by razzeee** [comment]
Yes, I only removed them because I wasn't sure which languages you ment :)

**Pull request closed without merging**
